[package]
name = "gpt-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.2", features = ["derive"] }
gpt-common = { path = '../gpt-common' }
serde_json = "1.0.96"

[profile.release]
debug = true
